### PR TITLE
Add support for uploading config.json

### PR DESCRIPTION
**Pull request by dmascord**
This change adds support for uploading config.json via the ota website.

Also, allow for importing *_env.ini (for prod_env.ini etc)

### CODE REVIEW

**Comment by anubisg1** [comment]
@dmascord please hold on this PR until i get mine merged with the upstream code from ecodina. 
It might need some adjustments before merging

**Comment by dmascord** [comment]
No rush, just let me know

**Comment by anubisg1** [comment]
the PR was accepted now. please fix all conflicts

**Comment by dmascord** [comment]
Conflicts resolved

**Review by anubisg1 — APPROVED** [review]

**Pull request merged**
